'use strict';
// User-facing overlevel/overdrive weapon copy. Numeric stat scaling stays in weapon-stats.js.
const OVER_DESC = {
  bolt: '분열 화살이 더 촘촘하게 적을 꿰뚫습니다.',
  orbit: '수리검 궤도가 확장되어 접근하는 적을 갈아냅니다.',
  lightning: '번개 폭풍이 더 많은 적을 찾아 이어집니다.',
  nova: '불꽃 파동이 더 자주, 더 넓게 터져 나갑니다.',
  missile: '추적 미사일이 더 집요하게 몰아칩니다.',
  laser: '프리즘 빔이 더 오래 남아 적을 절단합니다.',
  boomerang: '부메랑이 더 멀리 휘돌며 전장을 가릅니다.',
  frost: '냉기 지대가 더 넓게 퍼져 적의 진격을 늦춥니다.',
  lance: '플라즈마 창이 더욱 두껍고 길게 적진을 관통합니다.',
  orbital: '폭격 좌표가 더 촘촘하게 떨어져 큰 무리를 정리합니다.',
  shotgun: '산탄이 더 촘촘하게 퍼져 근접한 적을 밀어냅니다.',
  drone: '드론 포대가 더 많은 적을 더 빠르게 추적합니다.',
  blackhole: '중력장이 더 오래 남아 적 무리를 묶어둡니다.',
  chainsaw: '체인 톱날이 더 오래 전방을 갈아냅니다.',
  arrowrain: '네온 화살비가 더 많은 좌표에 떨어집니다.',
  shockmine: '감전 지뢰 폭발이 더 넓고 강하게 이어집니다.',
  ricochet: '반사 디스크가 더 오래 튕기며 적을 긁습니다.',
  timerift: '시간 균열이 더 오래 적의 진격을 늦춥니다.',
  railgun: '레일건 관통탄이 더 강한 적을 꿰뚫습니다.',
  toxic: '독성 안개가 더 오래 전장을 오염시킵니다.',
  phoenix: '불사조 깃털이 더 많은 방향으로 흩날립니다.',
  sonic: '음파 충격파가 더 자주 접근을 끊습니다.',
  icespear: '빙결 창이 더 많은 적을 관통하고 둔화시킵니다.',
  satlaser: '위성 레이저가 강한 적을 더 집요하게 조준합니다.',
};
